name: build-and-test
on: ["push", "pull_request"]
jobs:
  build-and-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - run: go test -p 1 ./...
